### ISSUE TITLE
Non-static method Grab\Spider::defaultParser() should not be called statically

### ISSUE THREAD

**Issue by ismaail** [strelov1/Spider#1]
The line [182](https://github.com/strelov1/Spider/commit/92fdf3925027d41d563b5e1104e9d1c5cfd4477b#diff-b3fdab898b735d02eb5c07656fc46d96R182) changed in the commit 92fdf392 give the following error:

```
Non-static method Grab\Spider::defaultParser() should not be called statically
```

Test with PHP: 7.0

**Comment by strelov1** [comment]
Thank you
I fixed it (https://github.com/strelov1/Spider/commit/b5a711f6eb36d750efc822b2ff1804c6c89c42a3)
